apiVersion: v1
kind: Service
metadata:
  name: main-service
  labels:
    name: main-service-label
spec:
  selector:
    name: main-deployment
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
