# Generated by Django 3.0.4 on 2020-06-21 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
