# Generated by Django 3.0.4 on 2020-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_quiz_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
