name: ci

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose Action
        uses: adambirds/docker-compose-action@v1.4.1
        with:
          compose-file: "kafka-hello-world/docker-compose.yml"
          down-flags: "--volumes"
          test-command: "nc -vz localhost 9092"



